backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
display_url: https://www.rahb.me
logo_url: https://www.rahb.me/images/logo.png

collections:
  - name: "pages"
    label: "الصفحات"
    delete: false
    editor:
      preview: false
    files:
      - file: "src/pages/places/index.md"
        label: "الأماكن"
        name: "places"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "places-post" }
          - label: "الأماكن"
            name: "places"
            widget: "list"
            fields:
              - { label: "اسم المكان", name: "name", widget: "string", required: "true" }
              - { label: " اسم المكان بالأنجليزي", name: "EnName", widget: "string" }
              - { label: " رابط المكان في خرائط قوقل", name: "url", widget: "string", required: "true" }
              - label: "تصنيفات المكان"
                name: "tags"
                widget: "select"
                multiple: true
                options: ["كافيه", "مطعم", "مطعم وكافيه"]
